CREATE TABLE people (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
    name VARCHAR(50) NOT NULL,
    surname VARCHAR(100) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE users (
    login VARCHAR(100) NOT NULL,
    password VARCHAR(64) NOT NULL,
    role VARCHAR(5) NOT NULL,
    PRIMARY KEY (login)
);

CREATE TABLE types (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
    name VARCHAR(50) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE pets (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
    name VARCHAR(50) NOT NULL,
    owner_id INTEGER NOT NULL,
    type_id INTEGER NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (owner_id) REFERENCES people(id),
    FOREIGN KEY (type_id) REFERENCES types(id)
);

-- Insert default pet types
INSERT INTO types (name) VALUES 
('dog'),
('cat'),
('rabbit'),
('bird'),
('fish'),
('hamster'),
('turtle');